sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -f Dockerfile.build  -t img   .

script:
    - docker run -v $(pwd)/dist:/dist  img
    - $(pwd)/dist/es_cluster_exporter.linux-x86_64 --help 2> result

    - echo "==> Validating the test results..."
    - sh -c "[ -s result ]"